# Generated by Django 5.1.1 on 2024-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpdataFake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('percentage', models.BigIntegerField()),
            ],
        ),
    ]
